import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Homepage.module.scss";
import { useEffect, useState, useRef } from "react";
import ImgHome from "./../../public/home.png";
import ImgPhone from "./../../public/phone.png";
import Link from "next/link";
import ReactAudioPlayer from "react-audio-player";

export default function Home() {
  const [windowWidth, setWindowWidth] = useState(0);

  const onHandleClick = () => {
    new Audio("/button.mp3").play();
  };

  useEffect(() => {
    if (typeof window !== "undefined") {
      setWindowWidth(window.innerWidth);

      const handleResize = () => {
        setWindowWidth(window.innerWidth);
      };

      window.addEventListener("resize", handleResize);

      return () => {
        window.removeEventListener("resize", handleResize);
      };
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Homepage}>
        <ReactAudioPlayer
          src="/song.mp3"
          autoPlay
          controls
          style={{ display: "none" }}
          volume={0.1}
        />
        {windowWidth >= 480 ? (
          <Image src={ImgHome} alt="Immagine per desktop" fluid />
        ) : (
          <Image src={ImgPhone} alt="Immagine per mobile" fluid />
        )}
        <div className={styles.button} onClick={onHandleClick}>
          <Link href="/pokedex" className={styles.button}>
            START
          </Link>
        </div>
      </div>
    </>
  );
}
